 pipeline {
      agent any 
      stages {
        stage('Clone sources') {
            steps {
                git url: 'https://github.com/EnzoPAGANO/tpcicd.git'
            }
        }
        
       stage('Compile') { // Compile and do unit testing
             steps {
               sh 'docker build -f apppython/Dockerfile -t pythonapp:1.0 .'
             }
           }
        stage('deploiement') {
            steps {
                sh 'ansible-playbook jenkins/playbook.yaml -i jenkins/inventaire.ini'
            }
        }
      }
 }